config/routes.rb
Rails.application.routes.draw do
  root to: "people#index"
  resources :people do
    collection { post :sort }
  end
  resources :admins
  resource :admin_sessions, only: [:new, :create, :destroy]
  get '/about' => 'static_pages#about', as: :about_page
  # get '/contact' => 'static_pages#contact_new', as: :contact_page
  # match '/contact' => 'static_pages#contact_send', via: [:post]
  get 'admin/manage/people' => 'admins#manage'
  get 'admin/manage/admins' => 'admins#index'
  get '/admin/login' => 'admin_sessions#new'
  get '/admin/logout' => 'admin_sessions#destroy'
  get '/admin/review', :to => 'admins#review'
  match '/people/:id/destroy' => 'people#destroy', via: [:delete]
  match '/admins/:id/destroy' => 'admins#destroy', via: [:delete]
  match '/admin/publish/:id' => 'admins#publish', via: [:get]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  
  validates :email, :presence => true,
  									:uniqueness => true

 	validates :password, :presence => true,
 											 :length => { :minimum => 6 }, 
 											 :confirmation => true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
	attribute :name,    validate: true
	attribute :email,   validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message


	def headers
		{
			subject: "New Contact Message",
			to: "admin@persianpreneur.com",
			from: %("#{name}" <#{email}>),
		}
	end
end

app/models/person.rb
class Person < ActiveRecord::Base

	mount_uploader :profile_picture, ImageUploader, dependent: :destroy

	validates :full_name, :presence => true, :uniqueness => true
	validates :location, :presence => true
	validates :description, length: {maximum: 175}

end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController


	def new
		if logged_in? 
			redirect_to(root_path)
		end
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(root_path)
		else 
			flash[:notice] = "Wrong Email or Password, Login failed."
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(root_path)
	end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to admin_manage_admins_path, notice: "Admin '#{@admin.email}' was successfully created." }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to admin_manage_admins_path, notice: "Admin '#{@admin.email}' was successfully updated." }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admin_manage_admins_path, notice: "Admin '#{@admin.email}' was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def review
    @people = Person.all.where(published: false)
  end

  def manage
    @people = Person.all.where(published: true).order(:position)
  end
  
  def publish
    @person = Person.find(params[:id])
    @person.update_attributes(published: true)
    flash.notice = "Person '#{@person.full_name}' was successfully published."
    redirect_to admin_review_path
  end

  private
    # Just authenticated users can create admins
    def zero_authors_or_authenticated
      unless Admin.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	before_filter :require_login, except: [:new, :create, :index]

	include PeopleHelper

	def index
		@people = Person.where(published: true).order(:position)
		fresh_when etag: [current_user, @people], last_modified: @people.maximum(:updated_at)
	end

	def show
		@person = Person.find(params[:id])
	end

	def new
		@person = Person.new		
		@person.published = false
		@person.position = Person.where(published: true).size + 1
	end

	def create
		@person = Person.new(person_params)
		if @person.save
			redirect_to root_path
			flash.notice = "Person '#{@person.full_name}' was successfully created."
		else
			render('new')
		end
	end

	def edit
		@person = Person.find(params[:id])
		@person.position = Person.where(published: true).size + 1
		@edit = true
	end

	def update
		@person = Person.find(params[:id])
		if @person.update(person_params)
			redirect_to admin_manage_people_path
			flash.notice = "Person '#{@person.full_name}' was successfully updated."
		else
			render 'edit'
		end
	end

	def destroy
		@person = Person.find(params[:id]).destroy
		flash.notice = "Person '#{@person.full_name}' was successfully destroyed."
		redirect_to admin_manage_people_path
	end

	def sort
		params[:person].each_with_index do |id, index|
			Person.where(id: id).update_all({ position: index + 1 })
		end
		render nothing: true
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def about
		fresh_when etag: [current_user]
	end

	def contact_new
	end

	def contact_send
  end

private
	def contact_form_params
		params.require(:contact_form).permit(:name, :email, :message)
	end

end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def title(page_title)
		content_for(:title) {page_title}
	end

end

app/helpers/people_helper.rb
module PeopleHelper

	def person_params
		params.require(:person).permit(:full_name, :description, :investor, :entrepreneur, :website,
																	 :profile_picture, :birth_date, :location, :twitter_handle, :linkedin_profile,
																	 :published, :position, :company, :email)
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin_sessions/new.html.erb
<% title "PersianPreneur | Login" %>
<div class="row text-center title">
	<h1>Login</h1>
</div>

<%= form_tag admin_sessions_path, method: :post do %>
  <div class="row">
    <div class="small-12 large-4 columns small-centered">
      <%= label_tag :email %>
      <%= text_field_tag :email %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 large-4 columns small-centered">
	    <%= label_tag :password %>
	    <%= password_field_tag :password %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 large-4 columns small-centered">
    	<%= submit_tag("Login", :class => "button small radius expand") %>
    </div>
  </div>
<% end %>

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div class="row">
      <div class="small-12 columns" id="error_explanation"></div>
        <div data-alert class="alert-box alert radius"><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</div>
       
        <% @admin.errors.full_messages.each do |message| %>
          <h5 class="small-offset-1"><small><%= message %></small></h5>  
        <% end %>
        
    </div>
  <% end %>

  <div class="row">
    <div class="medium-4 columns field">
      <div class="email-field">
        <%= f.label :email %>
        <%= f.text_field :email, placeholder: 'example@domain.com',required: '' %>
        <%#= content_tag(:small, "Please enter a valid email address", class: "error") %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="medium-4 columns field">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
  </div>
  <div class="row">
    <div class="medium-4 columns field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class="row">
    <div class="medium-4 columns left actoins small-centered">
      <%= f.submit class: "button small radius success expand" %>
    </div>
  </div>
<% end %>

app/views/admins/edit.html.erb
<% title "PersianPreneur | Edit Admin" %>
<div class="row">
	<div class="small-8 columns">
		<h1>Editing admin</h1>
	</div>
</div>

<%= render 'form' %>

app/views/admins/index.html.erb
<% title "PersianPreneur | Admins" %>
<div class="row title">
  <div class="small-8 columns">
    <h1>Manage Admins</h1>
  </div>
</div>

<div class="row">
  <div class="small-8 columns">
    <%= link_to("Add An Admin", new_admin_path, class: "button small radius success") %>
  </div>
</div>

<div class="row">
  <div class="small-8 columns">
    <table>
      <thead>
        <tr>
          <th>Email</th>
          <th class="text-center" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.email %></td>
            <td><%= link_to 'Show', admin %></td>
            <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
            <td><%= link_to 'Destroy', "/admins/#{admin.id}/destroy", method: :delete, data: {confirm: "Are you sure you want to destroy Admin \"#{admin.email}\"?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/manage.html.erb
<% title "PersianPreneur | Manage People" %>
<div class="row">
  <div class="small-8 columns title">
    <h1>Manage People</h1>
  </div>
</div>

<div class="row">
  <div class="small-8 columns">
    <%= link_to("Add A Person", new_person_path, class: "button small radius success") %>
  </div>
</div>

<% if @people.size > 0 %>
  <div class="row">
    <div class="small-8 columns">
      <table>
        <thead>
          <tr>
            <th></th>
            <th class="text-center">Person</th>
            <th class="text-center" colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody id="manage-people" data-update-url="<%= sort_people_url %>">
          <% @people.each do |person| %>
            <%= content_tag_for(:tr, person) do %>
              <td class="fa fa-arrows handle"></td>
              <td><%= person.full_name %></td>
              <td><%= link_to 'Show', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Destroy', "/people/#{person.id}/destroy", method: :delete, data: {confirm: "Are you sure you want to destroy Person '#{person.full_name}'?"} %></td>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/admins/new.html.erb
<% title "PersianPreneur | New Admin" %>
<div class="row">
	<div class="small-8 columns">
		<h1>Add an Admin</h1>
	</div>
</div>

<%= render 'form' %>

app/views/admins/review.html.erb
<% title "PersianPreneur | Review Suggestions" %>
<div class="row title">
  <div class="small-8 columns">
    <h1>Review Suggestions</h1>
  </div>
</div>

<% if @people.size > 0 %>
  <div class="row">
    <div class="small-8 columns">
      <table>
        <thead>
          <tr>
            <th>Person</th>
            <th class="text-center" colspan="4">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @people.each do |person| %>
            <tr>
              <td><%= person.full_name %></td>
              <td><%= link_to 'Show', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Destroy', person, method: :delete, data: {confirm: "Are you sure you want to destroy Person \"#{person.full_name}\"?" } %></td>
              <td><%= link_to 'Publish', "/admin/publish/#{person.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="small-8 columns">
      <h4>No New Suggestions</h4>
    </div>
  </div>
<% end %>

app/views/admins/show.html.erb
<% title "PersianPreneur | Show Admin" %>
<div class="row">
  <div class="small-2 columns">
    <h2><%= @admin.email %></h2>
	</div>
</div>

<div class="row"> 
	<div class="medium-1 columns">
		<%= link_to("Edit", edit_admin_path(@admin), class: "button small radius success") %>
	</div>
	<div class="medium-11 columns">
		<%= link_to("Destroy", "/admins/#{@admin.id}/destroy", method: :delete, class: "button small radius alert", data: {confirm: "Are you sure you want to destroy Admin \"#{@admin.email}\"?" }) %>
	</div>
</div>

app/views/layouts/_admin_top_bar.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar> 
    <ul class="title-area"> 
      <li class="name"></li> 
    </ul>     
      <section class="top-bar-section">
        <ul class="left">
          <ul class="title-area"> 
            <li class="home"> 
              <%= link_to "Home", root_path %>
            </li>
          </ul>
          <li class="divider"></li>            
          <ul class="title-area">
            <li class="review"> 
              <%= link_to "Review Suggestions", admin_review_path %>
            </li>
          </ul>
          <li class="divider"></li>
          <ul class="title-area"> 
            <li class="manage-people"> 
              <%= link_to "Manage People", admin_manage_people_path %>
            </li>
          </ul>
          <li class="divider"></li>
          <ul class="title-area"> 
            <li class="manage-admins"> 
              <%= link_to "Manage Admins", admin_manage_admins_path %>
            </li>
          </ul>
        </ul>
        <ul class="right">
          <li class="title-area">
            <%= link_to "Logged in as #{current_user.email}", edit_admin_path(current_user) %>
          </li>
          <li class="divider"></li>
          <li class="title-area">
            <li class="logout">
              <%= link_to "Logout", admin_logout_path %>
            </li>
          </li>
        </ul>
      </section>
  </nav>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-left">
	<div class="row">
		<div class="small-12 columns">
			<h6 class="subheader">&copy; 2017 Persianpreneur. Created by <a href="https://www.linkedin.com/in/hadifarnoud/" target="_blank">Hadi Farnoud</a> and sponsored by <a href="http://kamva.ir" target="_blank">Kamva</a> and <a href="http://abarcloud.com" target="_blank">AbarCloud</a></h6>
		</div>
	</div>
</footer>

app/views/layouts/_side_menu.html.erb
<div class="side-menu">
  <div class="small-2 columns right show-for-large-up">
    <ul class="side-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><%= link_to "About", about_page_path %></li>
      <li><a href="mailto:hadi.farnoud@gmail.com">Contact</a></li>
      <li><%= link_to "Twitter", 'http://twitter.com/persianpreneur', target: "_blank" %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-82958-16', 'auto');
      ga('send', 'pageview');

    </script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "Persianpreneurs, Iranian entrepreneurs making the world a better place!" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">        
        <div class="hide-for-large-up">
          <nav class="tab-bar">
            <section class="left-small">
              <a href="#" class="left-off-canvas-toggle menu-icon" ><span></span></a>
            </section>
          </nav>
          <aside class="left-off-canvas-menu">
            <ul class="off-canvas-list">
              <li><%= link_to 'Home', root_path %></li>
              <% unless logged_in? %>
                <li><%= link_to 'About', about_page_path %></li>
                <li><a href="mailto:hadi.farnoud@gmail.com">Contact</a></li>
                <li><%= link_to 'Twitter', 'http://twitter.com/persianpreneur', target: '_blank' %></li>
              <% end %>
              <% if logged_in? %>
                <li><%= link_to "Review Suggestions", admin_review_path %></li>
                <li><%= link_to "Manage People", admin_manage_people_path %></li>
                <li><%= link_to "Manage Admins", admin_manage_admins_path %></li>
                <li><%= link_to "Logged in as #{current_user.email}", edit_admin_path(current_user) %></li>
                <li><%= link_to "Logout", admin_logout_path %></li>
              <% end %>
            </ul>  
          </aside>
        </div>
          <% if logged_in? %>
            <div class="show-for-large-up">          
              <%= render partial: 'layouts/admin_top_bar' %>
            </div>
          <% end %>
          <% if flash.notice %>  
            <div class="row">
              <div class="8-small columns">          
                <div data-alert class="alert-box secondary">
                  <%= flash.notice %>
                  <a href="#" class="close">&times</a>
                </div>
              </div>
            </div>
          <% end %>        
        <div id="wrapper">
          <%= yield %>
        </div>
        <%= render partial: 'layouts/footer' %>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person, data: {abide: ''}) do |f| %>
  <% if @person.errors.any? %>
    <div class="row">
      <div class="small-12 columns" id="person-error">  
        <ul>
          <% @person.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="small-12 columns">
        <%= f.label :full_name %>
        <%= f.text_field :full_name, placeholder: 'Shervin Pishavar',required: '' %>
        <%= content_tag(:small, "This field is required", class: "error") %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 columns">
      <div class="small-12 large-6 columns">
        <%= f.check_box :investor %>
        <%= f.label :investor %>
      </div>
      <div class="small-12 large-6 columns large-pull-4">
        <%= f.check_box :entrepreneur %>
        <%= f.label :entrepreneur %>        
      </div>
    </div>
  </div>    
  <div class="row">
    <div class="small-12 large-6 columns">
      <%= f.label :description, id: "person-description-label" %>
      <span id="charcounter"></span>
      <%= f.text_area :description, rows: "4", maxlength: "175", placeholder: 'lorem ipsum', required: '' %>
      <%= content_tag(:small, "Please enter a short bio about this person.", class: "error") %>
    </div>
    <div class="small-12 large-6 columns">
      <%= f.label :location %>
      <%= f.text_field :location, placeholder: 'Silicon Valley, CA', required:'' %>
      <%= content_tag(:small, "We must know where this person lives. At least the country.", class: "error") %>
    </div>
    <div class="small-12 large-6 columns">
      <%= f.label :company %>
      <%= f.text_field :company %>
    </div>            
  </div>
  <div class="row">
  </div>
  <div class="row">
    <div class="small-12 large-6 columns">
   <%= f.label :website %>
   <%= f.text_field :website, placeholder: 'http://sherpa.com/', pattern: 'url' %>
      <%= content_tag(:small, "e.g. http://sharpa.com/", class:"error") %>
    </div>
    <div class="small-12 large-6 columns">
      <%= f.label :twitter_handle, "Twitter" %>
      <%= f.text_field :twitter_handle, placeholder: '@shervin' %>
    </div>    
  </div>
  <div class="row">
    <div class="small-12 large-6 columns">
      <%= f.label :linkedin_profile %>
      <%= f.text_field :linkedin_profile, placeholder: 'http://linkedin.com/in/shervin', pattern: 'url' %>
    </div>
    <div class="small-12 large-6 columns">
      <%= f.label :email %>
      <%= f.text_field :email, placeholder: 'shervin@example.com', type: "email" %>
    </div>
  </div>
  <div class="row">
    <div class="small-12 large-6 columns">
      <%= f.label :birth_date %>
      <%= f.text_field :birth_date, placeholder: 'YYYY-MM-DD', pattern: 'date', id: 'person-birthday', data:'mm-dd-yy' %>
    </div>
    <div class="small-12 large-6 columns">
      <%= f.label :profile_picture, 'Picture' %>
      <%= f.file_field :profile_picture if @person.profile_picture? %>
      <%= f.file_field :profile_picture, required: '' unless @person.profile_picture? %>
    </div>    
  </div>
  <% if logged_in? %>
    <div class="row">
      <div class="small-12 columns">
        <%= f.label :position %>
        <%= f.number_field :position, required: '' %>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
     <%= f.check_box :published %>
     <%= f.label :published %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="small-10 large-4 columns small-centered">
      <%= f.submit @edit ? "Update Person" : "Add To The List", class: "button small radius expand" %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<% title "PersianPreneur | Edit Person" %>
<div class="row">
	<div class="small-8 columns">
		<h1>Edit Person</h1>
	</div>
</div>

<%= render partial: 'form' %>

app/views/people/index.html.erb
<div class="main">
  <section id="main-section">
    <div class="row">
      <div class="small-12 large-10 columns left main-text">
          <h1 id="title">
            Persianpreneur  
          </h1>
          <div class="intro" id="title-description">
          <h4>
            /ˈpərZHənprəˈno͝or, -ˈnər/ <span class="noun"> noun</span></h4>
          
          <h5>
            <p>An Iranian entrepreneur making the world a better place by solving one problem at a time. <br/>
          
          
            They are hardworking smart people. You can find a list of them below.</p>
          </h5>          
        </div>
        <div id="add-person-button">
          <%= link_to "Add Someone To The List", "#", data: {:'reveal-id' => 'addPersonModal'}, class: ['button small radius'] %>
        </div>
        <div id="addPersonModal" class="reveal-modal" data-reveal>
          <% @person = Person.new %>
          <%= render partial: 'form' %>
          <a class="close-reveal-modal">&#215;</a>
        </div>                    
      </div>
      <%= render partial: 'layouts/side_menu' %>
    </div>
  </section> 
  <section id="content-section">
    <ul class="small-block-grid-1 medium-block-grid-6 large-block-grid-10">
      <%= render partial: 'person', collection: @people %>
    </ul>
  </section>
</div>

app/views/people/manage.html.erb
<% title "PersianPreneur | Manage People" %>
<div class="row">
  <div class="small-8 columns title">
    <h1>Manage People</h1>
  </div>
</div>

<div class="row">
  <div class="small-8 columns">
    <%= link_to("Add A Person", new_person_path, class: "button tiny radius success") %>
  </div>
</div>

<% if @people.size > 0 %>
  <div class="row">
    <div class="small-8 columns">
      <table>
        <thead>
          <tr>
            <th>Person</th>
            <th class="text-center" colspan="3">Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @people.each do |person| %>
            <tr>
                <td><%= person.full_name %></td>
              <td><%= link_to 'Show', person %></td>
              <td><%= link_to 'Edit', edit_person_path(person) %></td>
              <td><%= link_to 'Destroy', "/people/#{person.id}/destroy", method: :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="small-8 columns">
      <h4>No New Suggestions</h4>
    </div>
  </div>
<% end %>

app/views/people/new.html.erb
<%= render partial: 'form' %>

app/views/people/show.html.erb
<% title "PersianPreneur | Show Person" %>
<div class="row">
  <div class="small-12 columns">
    <%= image_tag(@person.profile_picture.normal.url) %>    
	</div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h2>
      <%= @person.full_name + (@person.birth_date.blank? ? "" : ", ") %>
      <% unless @person.birth_date.blank? %>
        <%= Time.now.utc.to_date.year - @person.birth_date.year - (@person.birth_date.to_date.change(:year => Time.now.utc.to_date.year) > Time.now.utc.to_date ? 1 : 0) %> 
      <% end %>
    </h2>
	</div>
</div>
<div class="row">
  <div class="small-12 columns">
    <div>
      <% unless @person.website.blank? %>
        <%= link_to "", @person.website, :class => ['fa', 'fa-home', 'fa-2x'] %>
      <% end %>
      <% unless @person.linkedin_profile.blank? %>
        <%= link_to "", "#{@person.linkedin_profile}", :class => ['fa', 'fa-linkedin-square'  , 'fa-2x'] %>
      <% end %>
      <% unless @person.twitter_handle.blank? %>
        <%= link_to "", "http://twitter.com/#{@person.twitter_handle}", :class => ['fa', 'fa-twitter-square', 'fa-2x'] %>
      <% end %>
    </div>    
	</div>
</div>
<% if @person.entrepreneur %>
	<div class="row">
	  <div class="small-12 columns">
	    <h3><%= "Entrepreneur" %></h3>
		</div>
	</div>
<% end %>

<% if @person.investor %>
	<div class="row">
	  <div class="small-12 columns">
	    <h3><%= "Investor" %></h3>
		</div>
	</div>
<% end %>
<div class="row">
  <div class="small-12 columns">
    <h3><%= @person.description %></h3>
	</div>
</div>
<div class="row">
  <div class="small-12 columns">
    <h3><%= @person.birth_date %></h3>
	</div>
</div>
<div class="row"> 
	<div class="medium-1 columns">
		<%= link_to("Edit", edit_person_path(@person), class: "button small radius success") %>
	</div>
	<div class="medium-11 columns">
		<%= link_to("Destroy", "/people/#{@person.id}/destroy", method: :delete, class: "button small radius alert", data: {confirm: "Are you sure you want to destroy Person \"#{@person.full_name}\"?" }) %>
	</div>
</div>